name: zookeeper-deployment

releases:
- name: zookeeper
  version: 0.0.5
  url: https://bosh.io/d/github.com/cppforlife/zookeeper-release?v=0.0.5
  sha1: 65a07b7526f108b0863d76aada7fc29e2c9e2095

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 621.125  # Replace with a specific stable version

update:
  canaries: 2
  max_in_flight: 2  # Increase for better parallel updates
  canary_watch_time: 5000-60000
  update_watch_time: 10000-120000  # Increased upper bound for stability

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 5
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk_type: large  # Use disk type instead of a fixed size
  networks:
  - name: default

- name: smoke-test
  azs: [z1, z2]  # Spread across multiple AZs for better resilience
  lifecycle: errand
  instances: 1
  jobs:
  - name: smoke-tests
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
