name: zookeeper-deployment

releases:
- name: zookeeper
  version: 0.0.5
  url: https://bosh.io/d/github.com/cppforlife/zookeeper-release?v=0.0.5
  sha1: 65a07b7526f108b0863d76aada7fc29e2c9e2095

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "621.125"  # Pin to a tested stable version

update:
  canaries: 2
  max_in_flight: 2        # Tune based on VM capacity
  canary_watch_time: 5000-60000
  update_watch_time: 10000-120000  # Allow more time for stability

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 5
  vm_type: default
  stemcell: default
  persistent_disk_type: large   # BOSH cloud-config defines disk types
  networks:
  - name: default
  jobs:
  - name: zookeeper
    release: zookeeper
    properties:
      # Add ZooKeeper-specific configs here (example):
      tick_time: 2000
      init_limit: 10
      sync_limit: 5
      max_client_cnxns: 60

- name: smoke-test
  azs: [z1, z2]   # Errand spread across AZs for resilience
  lifecycle: errand
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: smoke-tests
    release: zookeeper
    properties: {}
